<a href="https://colab.research.google.com/github/mykhailodolitsoi/EDU_pytorch/blob/main/00_pytorch_fundomentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introducing to tensors

PyTorch tensors are created using `torch.Tensor()`: https://docs.pytorch.org/docs/stable/generated/torch.tensor.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

## Random tensors

Why random tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and than adjust them to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> update random numbers ...`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
 # random tensor of shape (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4416, 0.4925, 0.7071, 0.9520],
        [0.4272, 0.5765, 0.6207, 0.1713],
        [0.1248, 0.5727, 0.5145, 0.0193]])

In [ ]:
# create a tensor with similiar to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224) # height, width, colour channels(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

 ## Zeroes and ones

In [ ]:
# create a tensor of all zeroes

zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
one = torch.ones(3, 4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range of tensors and tensors-like

In [ ]:
arange = torch.arange(-15, 16, 3)
arange

tensor([-15, -12,  -9,  -6,  -3,   0,   3,   6,   9,  12,  15])

In [ ]:
# creating tensors-like
zeroes = torch.zeros_like(arange)
zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:**: Tensor datatypes is one of the 3 big issues with PyTorch & deep learning:
1. Tensors are not right datatype
2. Tensors are not right shape
3. Tensors are not on right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# float32 tensor
float32_tensor = torch.tensor([3.0, 4, 5],
                              dtype = None, # what datatype is tensor (e. g. float32, float16)
                              device = None, # what device is your tensor on
                              requires_grad = False) # wheter or not to track gradients with this tensor operations
float32_tensor

tensor([3., 4., 5.])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
int32_tensor = torch.tensor([1, 2, 3], dtype = torch.long)

In [ ]:
(int32_tensor * float32_tensor).dtype

torch.float32

## Getting information from tensors (tensor attributes).

1. Tensors are not right datatype - to get datatype from a tensor. can use `tensor.dtype`
2. Tensors are not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors are not on right device - to get device from a tensor, can use `tensor.deivce`

In [ ]:
# create a tensor
tensor = torch.rand(2, 2)
tensor

tensor([[0.8502, 0.5126],
        [0.8514, 0.7142]])

In [ ]:
# get a datatype
tensor.dtype

torch.float32

In [ ]:
# get a shape
tensor.shape

torch.Size([2, 2])

In [ ]:
# get a device
tensor.device

device(type='cpu')

## Manipulating tensors (tensor operations)

Tensors operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication  

In [ ]:
# Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiplicate by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# trying out PyTorch built-in functions
tensor = torch.mul(tensor, 10)
print(tensor)
tensor = torch.add(tensor, 10)
print(tensor)
tensor = torch.subtract(tensor, 10)
print(tensor)
tensor = torch.divide(tensor, 10)
print(tensor)

tensor([10, 20, 30])
tensor([20, 30, 40])
tensor([10, 20, 30])
tensor([1., 2., 3.])


### Matrix multiplication

Two main ways of performaing multiplication in neural networks and deep learning:
1. Element - wise: multiplicate each element by `x`
2. Matrix multiplication: `dot product`  

There are two main rules performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` - ERROR, w'ont work
* `(3, 2) @ (2, 3)` - SUCCESS, will work
2. The resulting matrix has the shape of the **outer dimentions**:
* `(3, 2) @ (2, 3)` - results in `(3, 3)` matrix

In [ ]:
# element-wise
torch.mul(tensor, tensor)

tensor([1., 4., 9.])

In [ ]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14.)

### One of the most common errors in deep learning: shape errors

In [ ]:
a = torch.rand(3, 2)
b = torch.rand(3, 2)
# torch.matmul(a, b) # ERROR

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.matmul(tensor_A, tensor_B) # ERROR

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# to fix tensor shape issues use **transpose**
# a **transpose** switches the axes(dimentions) of a tensor

tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# torch.matmul(tensor_A, tensor_B) # ERROR
torch.matmul(tensor_A, tensor_B.T) # the matrix multiplication works when tensor_B is transposed


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(0)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A.float()
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 0.0778, -2.0911, -0.1846,  1.1335,  0.5910, -0.0674],
        [ 0.8259, -4.2958, -0.3501,  2.2268,  0.8397, -0.7728],
        [ 1.5739, -6.5005, -0.5155,  3.3201,  1.0884, -1.4782]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### Finding the min, max, mean, sum, etc. (tensor aggrigation)

In [ ]:
# create a tensor
tensor = torch.tensor([1, 6, 3, -4, 5],
                      dtype = torch.float16)
tensor

tensor([ 1.,  6.,  3., -4.,  5.], dtype=torch.float16)

In [ ]:
# find the min
torch.min(tensor)

tensor(-4., dtype=torch.float16)

In [ ]:
# find the max
torch.max(tensor)

tensor(6., dtype=torch.float16)

In [ ]:
# find the mean - note: the torch.meam() function requires a tensor of float datatype
torch.mean(tensor)

tensor(2.1992, dtype=torch.float16)

In [ ]:
# find the sum
torch.sum(tensor)

tensor(11., dtype=torch.float16)

### Finding the positional min and max

In [ ]:
# find the position of min value
torch.argmin(tensor)

tensor(3)

In [ ]:
# find the the position of max value
torch.argmax(tensor)

tensor(1)

### Refreshing, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View = return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - remove all `1` demensions from a tensor
* Unsqueeze - add a `1` dimention to a tensor
* Permute - Return a view of athe input with dimentions permuted(swapped) in a certain way

In [ ]:
# create a tensor
tensor = torch.arange(1., 10., dtype = torch.float16)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16),
 torch.Size([9]))

In [ ]:
# change a view of a tensor to (9, 1)
tensor_reshape = tensor.reshape(9, 1)
tensor_reshape, tensor_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]], dtype=torch.float16),
 torch.Size([9, 1]))

In [ ]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [ ]:
# change a view of a tensor to (3, 3)
tensor_reshape.reshape(3, 3), tensor_reshape.reshape(3, 3).shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]], dtype=torch.float16),
 torch.Size([3, 3]))

In [ ]:
tensor, tensor_reshape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]], dtype=torch.float16))

In [ ]:
# changing tensor_reshape changes tensor (because a view of the tensor shares the same memory as the original tensor)
# add an extra dimention
tensor_reshape = tensor.reshape(1, 9)
tensor_reshape, tensor_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16),
 torch.Size([1, 9]))

In [ ]:
tensor_reshape[:, 8] = 0
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 0.], dtype=torch.float16)

In [ ]:
tensor_reshape = tensor_reshape.reshape(3, 3)
tensor_reshape[:, 0] = 1000
tensor, tensor_reshape

(tensor([1000.,    2.,    3., 1000.,    5.,    6., 1000.,    8.,    0.],
        dtype=torch.float16),
 tensor([[1000.,    2.,    3.],
         [1000.,    5.,    6.],
         [1000.,    8.,    0.]], dtype=torch.float16))

In [ ]:
# stack tensors
x = torch.tensor([1, 2, 3])
x_stacked = torch.stack([x, x, x, x], dim = 0)
x, x_stacked, x_stacked.shape

(tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]),
 torch.Size([4, 3]))

In [ ]:
# torch.squeeze
tensor = torch.zeros(1, 3, 3)
print(f"Original tensor: {tensor}")
print(f"Original tensors shape: {tensor.shape}")
tensor_squeezed = tensor.squeeze()
print(f"Squeezed tensor: {tensor_squeezed}")
print(f"Squeezed tensors shape: {tensor_squeezed.shape}")

Original tensor: tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
Original tensors shape: torch.Size([1, 3, 3])
Squeezed tensor: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Squeezed tensors shape: torch.Size([3, 3])


In [ ]:
# torch.unsqueeze
print(f"Previous target: {tensor_squeezed}")
print(f"Previous shape: {tensor_squeezed.shape}")
tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=0)
print(f"Unsqueezed tensor: {tensor_unsqueezed}")
print(f"Unsqueezed tensor's shape: {tensor_unsqueezed.shape}")

Previous target: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Previous shape: torch.Size([3, 3])
Unsqueezed tensor: tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
Unsqueezed tensor's shape: torch.Size([1, 3, 3])


In [ ]:
# tensor.permute
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Original tensor: {tensor}")
print(f"Original tensor's shape: {tensor.shape}")
tensor_permuted = torch.permute(tensor, (2, 1, 0))
print(f"Permuted tensor: {tensor_permuted}")
print(f"Permuted tensor's shape: {tensor_permuted.shape}")

Original tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Original tensor's shape: torch.Size([2, 2, 2])
Permuted tensor: tensor([[[1, 5],
         [3, 7]],

        [[2, 6],
         [4, 8]]])
Permuted tensor's shape: torch.Size([2, 2, 2])


### Indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch and Numpy tensors

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.
 - Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
 - PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
import numpy as np

In [ ]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy array's dtype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
np_array = np.random.rand(10)
pt_tensor = torch.rand(10)

np_array.dtype, pt_tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
# change the value of array
np_array = np_array + 1
np_array, pt_tensor

(array([1.87889443, 1.77815089, 1.39620369, 1.10463287, 1.48326284,
        1.29609397, 1.27205144, 1.54200963, 1.4157374 , 1.45902178]),
 tensor([0.1610, 0.2823, 0.6816, 0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527,
         0.0362]))

In [ ]:
# tensor to NumPy array
tensor = torch.randint(10, (2, 2, 2))
np_array = torch.Tensor.numpy(tensor)
tensor, np_array

(tensor([[[9, 0],
          [1, 2]],
 
         [[3, 0],
          [5, 5]]]),
 array([[[9, 0],
         [1, 2]],
 
        [[3, 0],
         [5, 5]]]))

## Reproducibility

In short how a neural network works:

`start with random numbers -> tensor operations -> update random numbers to make them a beeter representation of data -> tensor operations -> ...`

To reduse randomness in neural networks and PyTorch comes the concept of a **random.seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2081, 0.9298, 0.7231, 0.7423],
        [0.5263, 0.2437, 0.5846, 0.0332],
        [0.1387, 0.2422, 0.8155, 0.7932]])
tensor([[0.2783, 0.4820, 0.8198, 0.9971],
        [0.6984, 0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535, 0.2417]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# set a random seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.0223, 0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610, 0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)

random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources dor reproducibility
- https://docs.pytorch.org/docs/stable/notes/randomness.html
- https://en.wikipedia.org/wiki/Random_seed

## Running  tensors and PyTorch objects on GPUs

GPUs = faster computing on numbers, thanks to CUDA + Nvidia hardware + PyTorch working behind the scene.

### Getting a GPU

1. Easiest - use google colab, kaggle for a free, time-limited GPU.
2. Use your own setup.
3. Use cloud computing - GCP, AWS, Azure

In [ ]:
!nvidia-smi

Sat Sep 27 18:20:15 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   63C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# check for GPU access with PyTorch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the number of devices
torch.cuda.device_count()

1

### Putting tensor, models on the GPU

The reason we want our tensors and models on GPU is because of faster computations.

In [ ]:
# create a tensor (default on the GPU)
tensor = torch.tensor([1, 2, 3])

# tensor NOT on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU (if availible)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensor back to CPU

In [ ]:
# if tensor is on GPU, can not convert to numpy
a =tensor_on_gpu.cpu()
tensor_on_gpu.device
a.numpy()

array([1, 2, 3])

## Exercises

In [ ]:
import torch

In [ ]:
# create a random tensorwith shape (7, 7)
tensorA = torch.rand(7, 7)
tensorA

tensor([[0.5060, 0.2599, 0.4779, 0.2247, 0.6457, 0.9367, 0.9832],
        [0.9045, 0.8180, 0.4810, 0.8188, 0.8461, 0.8161, 0.2206],
        [0.3700, 0.4780, 0.0508, 0.6415, 0.5111, 0.0034, 0.0932],
        [0.3748, 0.5333, 0.0235, 0.7676, 0.5872, 0.1161, 0.2075],
        [0.1564, 0.9401, 0.4796, 0.9222, 0.1435, 0.4702, 0.8650],
        [0.6925, 0.3547, 0.1190, 0.2482, 0.5721, 0.4371, 0.5135],
        [0.4993, 0.7613, 0.2759, 0.7968, 0.4797, 0.4942, 0.8348]])

In [ ]:
# create another tensor with shape (1, 7) and perform matrix multiplication
tensorB = torch.rand(1, 7)
tensorB = torch.transpose(tensorB, 1, 0)
tensorC = torch.matmul(tensorA, tensorB)
tensorC

tensor([[1.5291],
        [2.1415],
        [0.9506],
        [1.1165],
        [2.0819],
        [1.1195],
        [1.8808]])

In [ ]:
# set a random seed to 0 and repeat the previous operations
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

tensorA = torch.rand(7, 7)
tensorB = torch.rand(2, 7)
tensorB = torch.transpose(tensorB, 1, 0)

tensorC = torch.matmul(tensorA, tensorB)
tensorC

tensor([[1.8542, 1.1939],
        [1.9611, 1.1061],
        [2.2884, 0.9868],
        [3.0481, 1.8999],
        [1.7067, 0.7716],
        [2.5290, 1.3174],
        [1.7989, 1.6353]])

In [ ]:
# create two random tensors of shape (2, 3) and send them both to the GPU. Set torch.manual_seed(1234) when creating the tensors.
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

tensorA = torch.rand(2, 3)
tensorB = torch.rand(2, 3)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

tensorA = tensorA.to(device)
tensorB = tensorB.to(device)

tensorA, tensorB

cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [ ]:
# perform a matrix multiplication on the tensors you created previously

tensorA = tensorA.cpu()
tensorB = tensorB.cpu()

tensorB = torch.transpose(tensorB, 1, 0)

tensorC = torch.matmul(tensorA, tensorB)
tensorC

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [ ]:
# find the maximum and minimum values of the output of 7
torch.max(tensorC), torch.min(tensorC)

(tensor(0.5617), tensor(0.3647))

In [ ]:
# find the maximum and minimum index values of the output of 7
torch.argmin(tensorC), torch.argmax(tensorC)

(tensor(0), tensor(3))

In [ ]:
# make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape
RANDOM_SEED = 7
tensorA = torch.rand(1, 1, 1, 10)
tensorB = tensorA.squeeze()

print(tensorA, tensorA.shape)
print(tensorB, tensorB.shape)


tensor([[[[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313,
           0.6012, 0.3043]]]]) torch.Size([1, 1, 1, 10])
tensor([0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012,
        0.3043]) torch.Size([10])
